# Generated by Django 2.0.9 on 2026-04-19 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='status',
        ),
    ]
