# Generated by Django 2.0.9 on 2026-04-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20260419_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
