# Generated by Django 2.0.9 on 2026-04-23 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_donation_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sos',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.sos_status'),
        ),
    ]
